#docker-compose.yml
version: '3'
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - '.env'
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - '.env'
# Create a container for postgres persisted data.
volumes:
  postgres:
